config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :phone_numbers, only: [:new, :create]
  root :to => 'phone_numbers#new'
  post 'phone_numbers/verify' => "phone_numbers#verify"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord

  def twilio_client
    Twilio::REST::Client.new(TWILIO_SID, TWILIO_TOKEN)
  end

  def send_pin
    twilio_client.messages.create(
      to: phone_number,
      from: ENV['TWILIO_PHONE_NUMBER'],
      body: "Your pin is #{pin}"
    )
  end

  def generate_pin
    self.pin = rand(0000..9999).to_s.rjust(4, "0")
    save
  end

  def verify(entered_pin)
    update(verified: true) if self.pin == entered_pin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController

  def new
    @phone_number = PhoneNumber.new
  end

  def create
    @phone_number = PhoneNumber.find_or_create_by(phone_number: params[:phone_number][:phone_number])
    @phone_number.generate_pin
    @phone_number.send_pin

    respond_to do |format|
      format.js
    end
  end

  def verify
    @phone_number = PhoneNumber.find_by(phone_number: params[:hidden_phone_number])
    @phone_number.verify(params[:pin])

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsVerification</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/phone_numbers/create.js.erb
$('#hidden_phone_number').val('<%= @phone_number.phone_number %>')
$('#send-pin').hide()
$('#verify-pin').fadeToggle()
$('#pin').focus()

app/views/phone_numbers/new.html.erb
<div id="send-pin">
  <h3> What's your phone number?</h3>

  <%= form_for @phone_number, remote: true do |f|%>
    <div class="form-group">
      <%= f.text_field :phone_number %>
    </div>
    <%= f.submit "Send Pin", class: "btn btn-primary", id: "send-pin-link" %>
  <% end %>
</div>

<div id="verify-pin">
  <h3> Enter your PIN </h3>

  <%= form_tag phone_numbers_verify_path, remote: true do |f| %>
    <%= hidden_field_tag 'hidden_phone_number', '' %>
    <div class="form-group">
      <%= text_field_tag :pin %>
    </div>
    <%= submit_tag "Verify PIN", class: "btn btn-primary" %>
  <% end %>
</div>

<div id="status-box" class="alert alert-success">
  <p id="status-message"> Status: Haven't done anything yet !!!</p>
</div>

app/views/phone_numbers/verify.js.erb
<% if @phone_number.verified %>
  $('#verify-pin').hide()
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-success')
  $('#status-message').text('Success!!')
  $('#send-pin').show()
<% else %>
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Sorry, that wasn't the right pin.")
<% end %>
$('#status-box').fadeToggle()